### ISSUE TITLE
Exposing hand confidence

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#10]
The OculusVR API has the following fields:

```c

	// Tracking confidence.
	// This is the amount of confidence that the system has that the entire hand pose is correct.
	ovrConfidence				HandConfidence;

	// Per-finger tracking confidence.
	// This is the amount of confidence the system has that the individual finger poses are correct.
	ovrConfidence				FingerConfidences[ovrHandFinger_Max];
```

exposing the confidence levels in the hand tracking. I don't think openxr has an equivalent. It might be important for applications to discard low-confidence data. On the other hand, we can allow user agents to pick a confidence bar for OculusVR backends. It would be ideal if we could expose this somehow, though.

**Comment by cabanier** [comment]
I think it's ok not to make this configurable.
Low confidence hand poses don't have good quality.

When can always add it later if needed.

**Comment by Manishearth** [comment]
Makes sense. Leaving the issue open for now, eventually we can tag this as a "future" issue once I add milestones

**Comment by cabanier** [comment]
We're only interested in exposing high confidence hand values so you can close this issue.

**Comment by josephrocca** [comment]
@cabanier Can you explain your reasoning here? I am currently in somewhat desperate need of confidence values for hand poses.

**Use case**: Determining dynamic (tracking-confidence-based) joint distance threshold values for end of grabbing-based gestures to prevent e.g. unintentional dropping of objects when hand occludes some fingers, while also maintaining tight trigger thresholds for grabbing gestures when tracking confidence is high (a must-have for good object manipulation UX).

**Context**: I have a few different grabbing-based gestures for different contexts/features (e.g. index pinch, middle pinch, fingers-to-palm, thumb-to-index-phalanx-intermediate, etc.) and for a good UX, I obviously want the grab to end when the user actually ends the grab. But tracking is not good in certain poses, so I end up needing a large end-of-gesture distance threshold to ensure they don't drop the object when they didn't actually release it. 

The threshold to prevent accidental dropping in most reasonable circumstances is actually *huge*. It makes it so even if their hand is right in front of their face (i.e. good tracking), they need to open their fingers very wide to release the object. Rather than trading off accidental object dropping with the despicably large release threshold, I'd like to be able to reduce that threshold dynamically based on the confidence of the tracking.

This isn't a "nice to have" in my opinion - it's essential for even the most basic custom gesture recognition. In the meantime I'm going to start implementing my own hacky confidence values based on calculated/estimated hand self-occlusion. It won't be pretty, but this is absolutely critical for my use case.

**Comment by josephrocca** [comment]
In terms of implementation, my preference would be per-joint values which have some absolute meaning regardless of device/OS. I.e. I'd much prefer distance/rotation standard deviation (or similar) for each joint rather than a unitless [0, 1] value/probability/whatever.

It goes without saying, but I'll emphasize here that userland self-occlusion calculations (like I'll be doing in the meantime) are not a robust approach because different devices have different predictive abilities (e.g. hand tendons give info on joint positions even when occluded) and camera locations/fidelity/etc.

**Comment by cabanier** [comment]
Like @Manishearth Manish mentioned, OpenXR does not offer confidence values for joint poses so Quest browser can't expose them either. The old API did return them but it has been deprecated. 
The question is also what "confidence" means and how it could be implemented in a cross platform way. If we returned them, how can we make sure that authors don't just optimize their experiences for Quest?

OpenXR *does* offer a [flag per joint](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrHandJointLocationsEXT) that returns if the system was able to track a joint and also the [strength of a gesture](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrHandTrackingAimStateFB). 
Could either one of those be helpful?

**Comment by josephrocca** [comment]
> The question is also what "confidence" means and how it could be implemented in a cross platform way

Is my above-proposed solution to that problem (i.e. something like stdev or 95% CI +/- on each joint position) not viable?

* **strength of a gesture**: IIUC, this is already fully/robustly implementable in userland, since it's essentially a distance between thumb+{index,middle,etc} tips?
* **flag per joint**: My guess is that it runs into the cross-platform problem - i.e. I have no way to know what that flat actually means in an absolute sense, since different devices have may have different confidence thresholds for enabling/disabling those able-to-track flags.
