### ISSUE TITLE
`getJointPose` should return a cached value

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#28]
We made some changes to the WebXR spec to limit the number of new objects we created.
We should do the same for `getJointPose`

**Comment by Manishearth** [comment]
I thought we decided this was not feasible for pose values

Maybe we should do it anyway here and clearly spec it

**Comment by cabanier** [comment]
Yes, I don't see why it wouldn't be possible.
It's especially needed here because we create so many temporary objects for each frame.

**Comment by Manishearth** [comment]
Hm. Because of the base space argument we can't do it reliably here either, at best we can allow the UA to do it. I'm going to think about this for a bit

**Comment by Manishearth** [comment]
So I think that this is feasible here because this is a new API so we don't have to worry about people using it a certain way in the past. However, it will have to be clearly documented.

Because of the second parameter, we cannot write tighter spec language than "the user agent may reuse objects returned last time with the same parameters"

**Comment by cabanier** [comment]
> Because of the second parameter, we cannot write tighter spec language than "the user agent may reuse objects returned last time with the same parameters"

I agree. If the call is made on the same object with the same parameters, we can reuse the last return value.

**Comment by Manishearth** [comment]
Closing in favor of https://github.com/immersive-web/webxr-hand-input/issues/37
