### ISSUE TITLE
targetRayMode and getPose for Ray information

### ISSUE THREAD

**Issue by Maksims** [immersive-web/webxr-hand-input#38]
Currently Oculus Quest reports `targetRayMode` for tracking hands as `gaze` for input source.
Specs do not specify if Hand Tracking modifies targetRayMode for input source.

This requires clarification, such as: is it up to vendors to report targetRayMode the way they want, and API users (developers) have to write their own logic on emulating Ray for tracked hands. Or there will be unified rules in specs on the way vendors will provide ray information to developers?

Currently almost all input sources provide Ray information, making it very convenient for application developers to rely on that data regardless of input source type. And having hand input with available ray would be very convenient too.
Also if there will be more spec rules on the way ray information is calculated it provides more consistent experience for application users across XR applications with tracked hands.

**Comment by Manishearth** [comment]
This is up to vendors and not within the purview of this specification. The core spec defines that all input sources have a target ray, and hand sources are an input source, so they do too. 

We leave this up to vendors because the choice of pointing ray is somewhat platform-specific; so it's entirely possible that your hand will produce a different ray on different devices and we're not against it.
