### ISSUE TITLE
Should XRHand have a getter method?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#78]
XRHand is defined as a `iterable<XRHandJoint, XRJointSpace>` with a `get` method.

However, in order to do `hand["wrist"]` I had to add an additional getter method. 
Is this extra method needed or is it a limitation of Chrome?

**Comment by cabanier** [comment]
@domenic do you know?

**Comment by domenic** [comment]
Named getters, i.e. magic where properties sprout in that fashion, are legacy. You should do one of the following:

- Define individual `readonly attribute`s for each joint.
- Define a `get(XRHandJoint key)` method, which is used as `hand.get("wrist")`.

Ideally you should only do one of these two options, so that there aren't two ways for authors to do the same thing (leading to each library and web developer to make a style choice as to which version they prefer).

**Comment by cabanier** [comment]
> Named getters, i.e. magic where properties sprout in that fashion, are legacy. You should do one of the following:

That is unfortunate. What is the reason that it's legacy? It just seems like a more javascript-y way to work with a map.

> * Define individual `readonly attribute`s for each joint.
> * Define a `get(XRHandJoint key)` method, which is used as `hand.get("wrist")`.

The API currently has that `get` method so it looks like we're ok.

**Comment by domenic** [comment]
Sorry for the delay!

In JavaScript, maps (such as the [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) class) are accessed using `get()` methods. Property key syntax, i.e. `obj["foo"]` or equivalently `obj.foo`, is reserved for static, well-defined, camelCased properties, not entries in a dynamic map.

This case is a bit strange, because the joints are actually static and well-defined; i.e., the "map" entries don't change over time. But, it seems like the predominant access pattern is going to be iteration, more like a dynamic map, and you've given them kebab-cased names.

**Comment by cabanier** [comment]
> This case is a bit strange, because the joints are actually static and well-defined; i.e., the "map" entries don't change over time. But, it seems like the predominant access pattern is going to be iteration, more like a dynamic map, and you've given them kebab-cased names.

Should we have used camelcased names? Since we're changing the API and it hasn't shipped yet, we can easily do so.

**Comment by Manishearth** [comment]
IDL enums are supposed to be kebab-case (typically)

**Comment by domenic** [comment]
I think it's a tricky case. You're currently kind of in a middle ground, where you're behaving more like a map than an object. That seems to match what I understand of your expected usage patterns, e.g., lots of iteration.

If you switched to object-style, then you'd have the following changes:

- No more `iterable<XRHandJoint, XRJointSpace>`, i.e. no more `hand.keys()`, `hand.values()`, `hand.entries()`, `hand.forEach((value, key) => { ... })`, or `hand[Symbol.iterator]()` methods. Instead, developers would be expected to use the more-awkward built-in JS object iteration facilities, such as `Object.keys(hand)`, `Object.values(hand)`, and `Object.entries(hand)`, and `Object.entries(hand).forEach(([key, value]) => { ... })`.

- No more `get()` method. I.e. instead of `hand.get(joint)`, developers would do `hand[joint]`.

- (And with the elimination of the above two, there'd be no more `XRHandJoint` enum.)

- No more `size` property. I.e. instead of `hand.size`, developers would do `Object.keys(hand).length`.

In exchange you'd make it slightly nicer and more idiomatic to access an individual joint, i.e. one would do `hand.pinkyFingerMetacarpal` instead of `hand.get("pinky-finger-metacarpal")`.

Perhaps the biggest disadvantage of object style is that it prohibits you from ever adding non-joint properties of the hand object, since all existing code would start treating those as joints. (That is, code would assume every member of `Object.values(hand)` is a joint.)

So overall I lean slightly toward keeping the current map style.

**Comment by cabanier** [comment]
Thanks! I'm ok using the current API as iteration will be the main use.
