### ISSUE TITLE
Radius for finger tips

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#90]
Currently the spec is silent what the radius for finger tips should be so it's up to the UA to put in a value.
Can we define it to be `0`? That way we can have a consistent experience.

**Comment by Manishearth** [comment]
I think that's fine, cc @thetuvix

**Comment by thetuvix** [comment]
I don't believe that HoloLens or Quest uses 0 tip radii in OpenXR - I believe instead the finger tip position is placed at the right spot inside the finger so that a sphere of that radius roughly touches the tip and pad of that finger for collision purposes.

**Comment by Manishearth** [comment]
Should we just allow both then?

**Comment by cabanier** [comment]
> I don't believe that HoloLens or Quest uses 0 tip radii in OpenXR - I believe instead the finger tip position is placed at the right spot inside the finger so that a sphere of that radius roughly touches the tip and pad of that finger for collision purposes.

The internal API that the Oculus implementation is based on, is returning a `0` radius. I will ask internally what we did for the OpenXR implementation.

**Comment by cabanier** [comment]
> Should we just allow both then?

Yes
Maybe the spec should state what @thetuvix said and not that the radius can be `0`.

**Comment by cabanier** [comment]
> I don't believe that HoloLens or Quest uses 0 tip radii in OpenXR - I believe instead the finger tip position is placed at the right spot inside the finger so that a sphere of that radius roughly touches the tip and pad of that finger for collision purposes.

@thetuvix you're correct that OpenXR for Quest doesn't return `0` for the radius of the tip but the older API (which is used by the browser) does.
I can't find your definition of the radius in the OpenXR document. Can you point me to where it says that this is for collision purposes?

**Comment by Maksims** [comment]
The radius of a fingertip that would approximate distance from the tip and a pad of a finger seems a reasonable approach to this, based on few use cases I have experimented demos with:

1. Identify different fingertips touching (pinch gesture), is easier when dealing with two tip radii and checking if the distance is less than a sum. If it is a tip with 0 radii, then we will have to calculate a point closer to the parent joint and estimate a radius. Or checking a distance between two tips will trigger when they even don't touch.
2. Physics created using capsules, is simple enough by using the centre of joints and radius of it. If the tip is an actual tip, then we again need to make the capsule a bit shorter and estimate the tip radius.

In fact, integrating Hands API, I've assumed that 0 radius of a tip, is somewhat a "bug" of early spec/implementation, and hard-coded a radius: https://github.com/playcanvas/engine/blob/master/src/xr/xr-joint.js#L138 because otherwise, it was harder to do maths for gestures, collision detection and other use cases.

**Comment by Manishearth** [comment]
So when I was designing this my assumption would be that tip would be a sphere to allow collisions. I think if we can go in that direction, that would be better, but I'm not sure what the variation across platforms is.

**Comment by cabanier** [comment]
> So when I was designing this my assumption would be that tip would be a sphere to allow collisions. I think if we can go in that direction, that would be better, but I'm not sure what the variation across platforms is.

I think that's reasonable. A radius of '0' would still be allowed but as @mrmaxm noted, it might require some additional fudging to get reliable collisions.

**Comment by thetuvix** [comment]
@cabanier:
> I can't find your definition of the radius in the OpenXR document. Can you point me to where it says that this is for collision purposes?

Here is the relevant language in the [OpenXR `XR_EXT_hand_tracking` spec](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_hand_tracking), specifically calling out the case of collision testing using a sphere centered at the index finger tip location:
> The radius of each joint is the distance from the joint to the skin in meters. The application can use a sphere at the joint location with joint radius for collision detection for interactions, such as pushing a virtual button using the index finger tip.

**Comment by cabanier** [comment]
Does that mean that the tip joint would be inset by the radius?

**Comment by Manishearth** [comment]
Yes

**Comment by cabanier** [comment]
@Manishearth did this result in a change to the spec?
The Oculus browser's OpenXR implementation no longer returns `0` so we're ok with the @thetuvix's suggestion

**Comment by Manishearth** [comment]
I don't think so!

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr-hand-input/pull/111
